site_name: epochron
site_description: REST ful Webcron Service with Webhooks
repo_url: https://github.com/robertjkeck2/epochron
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/robertjkeck2">robertjkeck2</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
