# Generated by Django 2.0.7 on 2018-08-01 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cron_day', models.CharField(blank=True, default='*', max_length=100)),
                ('cron_expression', models.CharField(blank=True, default='* * * * *', max_length=500)),
                ('cron_hour', models.CharField(blank=True, default='*', max_length=100)),
                ('cron_minute', models.CharField(blank=True, default='*', max_length=100)),
                ('cron_month', models.CharField(blank=True, default='*', max_length=100)),
                ('cron_weekday', models.CharField(blank=True, default='*', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('http_data', models.TextField()),
                ('http_headers', models.TextField()),
                ('http_method', models.CharField(blank=True, default='GET', max_length=7)),
                ('http_params', models.TextField()),
                ('http_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('next_run', models.DateTimeField()),
                ('webhook_data', models.TextField()),
                ('webhook_headers', models.TextField()),
                ('webhook_method', models.CharField(blank=True, default='GET', max_length=7)),
                ('webhook_params', models.TextField()),
                ('webhook_url', models.URLField()),
            ],
        ),
    ]
