# Generated by Django 2.0.7 on 2018-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180801_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='previous_run_duration',
            new_name='last_run_duration',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='next_run',
            new_name='next_run_at',
        ),
        migrations.AddField(
            model_name='job',
            name='last_run_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
