# Generated by Django 2.0.7 on 2018-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='max_daily_usage',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='num_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
